### ISSUE TITLE
Error 56 on Client Stop

### ISSUE THREAD

**Issue by russellgsystems** [LabVIEW-Open-Source/LV-MQTT-Broker#164] opened 2021-01-07 16:45 UTC
Hello @francois-normandin,

I was finally able to reproduce the Error 56 with a simple VI example attached.  My VI is in LV 2019, but you can try it in LV 2020 to see if you get the same error.

To run it just run the Main.vi and it will automatically run other VIs.  

I saw the error after 15 to 30 minutes of running the VI so it takes a little while before you see the error. 

The error occurs in the code where I am connecting and disconnecting for each command and response in a loop in the Main.vi. I have two commands happening back to back as well and I think that might have something to do with it as well. Since I send the commands quickly after connecting, the client must be disconnecting before I can actually send the packet.  I haven't looked at the underlying code in your library yet to see if I can see anything that might causing the issue, but plan to next. 

If you know what might be causing the issue, I would appreciate some insight. We are trying to use it for a test that will run for days so we need to be able to reliability have the connection present through the entire run.  Again I really appreciate all of your help with this library. I am really impressed with the features and capabilities of the library. 

[Command_Response.zip](https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/files/5782813/Command_Response.zip)

![image](https://user-images.githubusercontent.com/68344965/103917111-d6adca00-50d2-11eb-9a5a-e5a58534317e.png)

**Comment by russellgsystems** [comment] 2021-01-08 06:50
@francois-normandin 
The error 56 is being returned by the Send Packet VI when the SessionMailbox queue returns an error. I noticed that the isSessionActive returns error 1 very frequently while I was watching it running.  

![image](https://user-images.githubusercontent.com/68344965/103983437-dbae6000-514a-11eb-979f-96e3cd9cef80.png)

![image](https://user-images.githubusercontent.com/68344965/103982547-4d85aa00-5149-11eb-8673-38fb1be45fbe.png)

Looking at the Session process it looks like there are several errors at the top that can cause the disconnect session to occur which causes the SessionMailbox queue to be released.  I haven't gotten to a root cause yet, but I am thinking if it was easy to add to the session process something that logged the error at the top of the Session process and every time the SessionMailbox was released that might point us to something.  My hunch is the queue is being released while I am trying to send a packet.  But I am not sure why that is exactly yet.

![image](https://user-images.githubusercontent.com/68344965/103982756-be2cc680-5149-11eb-9400-9d986d07bde0.png)

**Comment by francois-normandin** [comment] 2021-01-08 11:56
HI @russellgsystems, 
I've been thinking for some time of a way to add a trace execution in the broker, and I haven't quite found an elegant way yet, which would be extensible and preserve the deeply asynchronous nature of the processes running around. This is at the back of my head every time I open the code, but until now, conventional debugging has always proven to be less time consuming than thinking about a tracer that spans the sessions and subscriptions that are in constant flux.

I haven't had time yet to open your example. Thanks, by the way, for providing code that reproduces the issue.
The mailbox error you are seeing is likely an error to be ignored because the everything is tied to the lifetime of the session itself. Everything around the session is completely dependent on the session being live, so the session process is the only place where a connection is involved. The connection can go down at any time for reasons that are totally out of control of your piece of code. It can be a physical network disconnection, it can be the server being shut down, it can be a protocol violation due to a bug on either side... So if the session mailbox goes stale, each process shuts down on its own. There is probably a better way to clean up everything, but my gut feeling is that this is not the problem. The reason your "Send Packet" returns a 56 error could be that the communication went down even before you tried to send a packet, but the client found out this way as opposed to another way. I don't rule it out, but it seems a symptom, not a cause.

Long burn down tests have not been performed. I've done some rapid connect-disconnect in a tight loop, as you probably remember from another bug report... and one thing I found is that I was sometimes hitting a DoS protection mechanism where I would exhaust all available TCP ports available to LabVIEW and would then start to see those ports released very slowly (on the order of a few seconds) before they could be reused. Totally unexpected and not something the LabVIEW code was responsible for. Throttling the creation and destruction period of clients helped avoid the problem... but I never ran this test for > 30 minutes.

My first hunch would be to check if your issue is not related to a memory leak. MQTT protocol has a provision for restoring a connection when the ClientID is reused. The feature is not yet implemented fully and tested, so I'm wondering if there might be an ever growing cache of past sessions which could be getting so large after a while (15, 30 minutes?) that it would lag on the server side, and the client could not connect within the time out.
Again, it might be a totally random error... but if that's the case, then your test should see the error 56 happen randomly at any time, with a bell-curve probability spectrum centered around the error occurence rate.

I'll try to find time to check your example over the weekend.

**Comment by russellgsystems** [comment] 2021-01-08 16:43
Hello @francois-normandin,

Thank you for your continued help on this one and insight above.  I think your thoughts about the number of sessions is right on.  There is a tremendous amount of session class process.vi clones being created since we are connecting and disconnecting repeatedly in the code. I am thinking that the issue might be how quickly and frequently we are doing this.  We did it this way because we are calling steps in Teststand and didn't want pass the connection around throughout the steps. But I am thinking this might be what we have to do unless we can get this session issue resolved.  Please let me know what you find as well.

**Comment by francois-normandin** [comment] 2021-01-10 21:09
I went through your example and was able to reproduce the issue. Probing a bit around, there are optimizations to do to the disconnection routine, but I have not found that the messages didn't go through and responses were unsuccessful.

From what I can see, this is mostly about hoe to properly handle disconnection. There are actually a few different things I've noticed:

1. Monitoring the connection handler, I can see that the number of active connections increases every time there is a warning 55012 on the client side during the disconnection process. It is as if the client session disconnects before sending the "Disconnect" packet to the server. I'm pretty sure that adding a small delay after the Disconnect message would solve this problem, but there is also another way to make sure we reuse the connections: by reusing the same ClientID. (more on that below)
2. Also in the connection handler, I see the effect of what I described in a previous post where each disconnection message from clients triggers the action on the server side to store the session for reuse. Being in a tight loop, this array of "stored sessions" increases quickly unless we set the ClientID to not be a new ID each time we connect again. This is OK... the protocol says we should store the closed sessions to allow a client to reconnect later with the same ID. However, I'll need to add some mechanism to prevent excessive number of stored sessions, because every time a new connection is created, the server scans for the stored sessions, which adds an increasing delay when you reconnect in a tight loop.
3. The error always occurs in the "Stop" part of the code. This means that the query was done correctly and it is just the nature of the protocol that we could have this error. I'll discuss more about that below... I suggest you can ignore this error and continue processing your steps.

For the record, without those modifications, I was seeing an error occur between 800 and 1600 iterations (~ bell curve distribution = random error, not deterministic error). After those modifications, I have not seen a single instance of disconnection with > 20000 iterations, and without even adding a 1 sec loop time. I increased the loop speed to its maximum by deleting the throttling "1000ms Wait"...

Modified code attached (LV2020).

[Issue 164 MQTT Broker.zip](https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/files/5793316/Issue.164.MQTT.Broker.zip)


### MQTT Disconnection discussion

MQTT's protocol is that there is no ACK on a disconnect message. That means that the connection will go down as soon as the server processes the message. And because there is no "ack" to be received, the client is free to close the connection right after the bytes are sent. The client and server disconnections are not deterministic. I believe that the way the client currently closes the connection should be more resilient to this fact. The error 56 (no connection) should not be an error at the output of the Stop method because it is entirely possible that the server closed the connection. The fact that it happens less often is just because the client generally acts more quickly that the server because of communication latency. 

![image](https://user-images.githubusercontent.com/11728548/104134828-091d2880-535a-11eb-9a91-d535a31b68bb.png)

In your example code, I recommend you use "Success" flag as the condition to stop or continue the tests. The Stop method should not report an error.

Also, name the ClientID so that stored connections are reused, and increase the subscription timeout from 100ms to > 1s

![image](https://user-images.githubusercontent.com/11728548/104134957-f6572380-535a-11eb-8b8e-f042f9c3203e.png)

If you are running > 10 000 steps before you stop the server, you might want to modify the Connection Handler's process and disable the session storage. Set this boolean"True" and you'll be fine (I've run it with 20000 stored connections on my machine and it was still OK): 

![image](https://user-images.githubusercontent.com/11728548/104135330-a2017300-535d-11eb-847d-f2ea726029be.png)


### Future actions resulting from this investigation (note to developer)

* Add a mechanism to regulate the stored sessions on the server side. Too many sessions will cause slowdowns, so a on-disk storage could be envisioned if the number of in-memory sessions becomes too large.
* Add a way for the server session to notify the connection handler that a client disconnected without sending a Disconnect packet (should correct the Active Session count that is too high when a client disconnection warning occurs)
* Process the client disconnection steps in a way to ignore the errors caused by non-determinism of the disconnection process. Those errors are not protocol errors, but rather an expected consequence of the asynchronous nature of the distributed disconnection process.

**Comment by russellgsystems** [comment] 2021-01-12 16:44
Hello @francois-normandin,

 I named the ClientID and increased the subscription timeout to 2000 in my production code. I ran my program for about 14 minutes and then I got error 56.  Then I set the boolean to true on the connectionhandler process and it ran for 16 minutes and then I got error 56.  I should note that in my production code the two messages that are repeated don't have any delays like the test code I sent you previously.  I will try to run it again with a delay of 1 second after I send each of the repeated messages sequentially. 

Do you have any other thoughts on what I might try next to improve the situation?

Russell

**Comment by francois-normandin** [comment] 2021-01-12 16:50
You will still see error 56, but this is an error you should discard if the query succeeded. I didn't see any transaction that failed (before the Stop method was called), after I had done what you just described.
I think you should be worried if you get an error 56 before you attempt to close the connection, but otherwise this is just about managing expected errors correctly. That's a bug alright, but it's a disconnection bug, not a publish-subscribe communication problem.

**Comment by russellgsystems** [comment] 2021-01-12 16:58
Hello @francois-normandin,

I am getting the error 56 when I try to send the packet right after the connect.  "Error 56 occurred at APISequencer.lvlibp:MQTT Client.lvlib:Session.Client.lvclass:Send Packet.vi:6230002" so this is before the stop method.

I can ignore the error 56 in this case?

I just ran with the 1 second delay and got the error 56 after 4 minutes of running it.

Thanks,

Russell

**Comment by russellgsystems** [comment] 2021-01-12 17:10
Hello @francois-normandin,

In answering my own question above I can't ignore 56 when it is returned from the Send Packet.vi.  If I ignore it then it won't send the packet.  Any other thoughts?

![image](https://user-images.githubusercontent.com/68344965/104347832-ac8b4c00-54c6-11eb-8bb5-ccc0844a349e.png)

![image](https://user-images.githubusercontent.com/68344965/104347861-b44af080-54c6-11eb-8e13-aaa6f230d0a3.png)

Thanks,

Russell

**Comment by francois-normandin** [comment] 2021-01-12 17:37
@russellgsystems I see in your screenshot that you've packaged it inside a PPL. Do you see the same problem when not in PPL? I'm asking because I haven't seen any errors coming from the send packet in the tests I've done from your example code. Not saying it does not happen, but all errors were happening strictly in the stop method. I ran it for 30000+ cycles.
I'd love to get to the bottom of this.

**Comment by russellgsystems** [comment] 2021-01-12 18:07
@francois-normandin,

Yes I did get that same error without the PPL. See the screenshot in my first post above:

https://user-images.githubusercontent.com/68344965/103917111-d6adca00-50d2-11eb-9a5a-e5a58534317e.png

**Comment by francois-normandin** [comment] 2021-01-13 02:03
@russellgsystems , I believe the error 56 comes from this node, which is called in the "Client:Stop" method.
![image](https://user-images.githubusercontent.com/11728548/104396718-382dc880-5519-11eb-90b9-e29a6c904351.png)

When I run your example on my machine, and I stop only on the "Success = false" flag (see mods in screenshot below), I can run for 30000+ iterations and it simply does not error out, if the Stop method sometimes throws an error from the "Disconnect" packet.

![image](https://user-images.githubusercontent.com/11728548/104396596-f3a22d00-5518-11eb-9878-2c8bb9951382.png)

If you can confirm this is the case, then yes I think you should ignore the error in the disconnection for now. I'll make that fix for the next release, of course.

**Comment by francois-normandin** [comment] 2021-01-13 02:05
Just thinking out loud... how about removing the "Disconnect" method?
After all, what is erroring it is the fact of disconnecting (in Stop method) when we have already disconnected before...
![image](https://user-images.githubusercontent.com/11728548/104397055-ecc7ea00-5519-11eb-8085-494666543dfe.png)

I'll run a quick test...

**Comment by russellgsystems** [comment] 2021-01-13 14:36
Hello @francois-normandin,

I removed the disconnect and have been running successfully for almost 2 hours with the production code.  I am going to let it continue running to see if and when I get the error. 

Thank you so much for all your hard work!,

Russell

**Comment by russellgsystems** [comment] 2021-01-13 19:48
@francois-normandin I ran it for 8 hours with no 56 error. So I am thinking you can probably close this one

Thanks again for all your help!

Russell

**Comment by francois-normandin** [comment] 2021-01-13 19:51
@russellgsystems that's great news. I'll close it off after I've transposed the disconnection fix into an issue in the client repo, just to keep track of it. It still needs fixing.

Thanks

**Closed** 2022-05-08 18:14 UTC
